ucupumar/ucupaint

.github/workflows/main.yml
Adding github actions to create draft release with zip file.
=> Auto draft release

Layer.py
=> add base/mixin class for multiple images to layer

.gitignore, __init__.py, addon_updater.py, addon_updater_ops.py, preferences.py
Add addon updater base on https://github.com/CGCookie/blender-addon-updater
=> Addon updater

addon_updater.py, addon_updater_ops.py
several bugs on blender legacy:
- force save preference after update
- disable backup
=> Bugs on blender legacy 

addon_updater.py, preferences.py
=> hide autoupdate on developer mode

addon_updater.py
handling on non-existent branch error
=> bug fix, last check not correctly written

addon_updater_ops.py, ui.py
popover only show branch choice
move check for update button
=> change layout on update menu

Bake.py, BakeToLayer.py, Layer.py, Mask.py, Modifier.py, Root.py, common.py, input_outputs.py, node_arrangements.py, node_connections.py, subtree.py, transition.py
First optimization will make sure only necessary nodes are being used. There are no changes on the node group library.
=> Optimization First Pass

Bake.py, BakeToLayer.py, Layer.py, Mask.py, Modifier.py, Root.py, common.py, input_outputs.py, node_arrangements.py, node_connections.py, subtree.py, transition.py
This reverts commit 989a27f9d3796a434fb9dee92383269cd4eca49a.
=> Revert "Optimization First Pass (#69)"

Bake.py, BakeToLayer.py, Layer.py, Mask.py, Modifier.py, Root.py, common.py, input_outputs.py, node_arrangements.py, node_connections.py, subtree.py, transition.py
The last pull request is kinda problematic (#69), this is the second attempt. 
First optimization will make sure only necessary nodes are being used. There are no changes on the node group library.
=> Optimization First Pass (Redo)

common.py
=> Add missing blend type.

.github/workflows/main.yml
add no auto udpate zip for blender extension platform
=> zip-no-auto-update

Bake.py, BakeToLayer.py, Layer.py, Mask.py, Modifier.py, Root.py, __init__.py, bake_common.py, blender_manifest.toml, common.py, image_ops.py, input_outputs.py, lib.py, load_blend_updates.py, modifier_common.py, node_arrangements.py, node_connections.py, preferences.py, subtree.py, transition.py, transition_common.py, ui.py, vcol_editor.py, vector_displacement.py, vector_displacement_lib.py
Version 2.0 branch consists the implementations of 
- #31
- #32
- #62 
- #63 
- #84
=> Version 2.0

Layer.py, Mask.py, common.py, input_outputs.py, lib.py, node_arrangements.py, node_connections.py, ui.py
=> Add decal vector mapping

ui.py
https://github.com/user-attachments/assets/0f7f14e9-9019-4129-bb7c-cc04cf799f31
=> Add Open Image as Decal shortcuts

Bake.py, BakeInfo.py, BakeToLayer.py, ImageAtlas.py, Layer.py, Mask.py, Root.py, UDIM.py, addon_updater.py, addon_updater_ops.py, bake_common.py, common.py, image_ops.py, input_outputs.py, lib.py, node_connections.py, preferences.py, subtree.py, ui.py, vcol_editor.py, vector_displacement_lib.py, versioning.py
Use generic functions to check for blender and data versions
=> Refactor version functions

Layer.py
Also fixed capitalization on buttons for consistency with the rest of Ucupaint UI
=> Don't ask for a confirmation to move a layer outside of a group

Bake.py, BakeToLayer.py, Layer.py, Mask.py, preferences.py
=> Add an option to turn off auto UDIM detection

Bake.py, BakeToLayer.py, ImageAtlas.py, Layer.py, Mask.py, Root.py, common.py, image_ops.py, lib.py, modifier_common.py, node_arrangements.py, node_connections.py, preferences.py, ui.py, vcol_editor.py
Pylance reports these as not accessed
=> Cleanup: Unused imports

Bake.py, BakeInfo.py
=> Allow baking disabled layers

Layer.py, Mask.py, ui.py
This adds buttons to open images as masks for new layers for both regular UV and Decal. Also fixes a coulple of small issues - VDM resolution being 1234 and masks not being expanded when a new one is added. They also expand Vector when added because you'll normally need to tweak scale after adding them
=> Add buttons to open image as mask for a new layer

.gitignore, Test.py, __init__.py, tests/test_quicksetup.py, ui.py
https://github.com/user-attachments/assets/8f43f1c8-9bf3-4508-b508-7f644f971515
I've added an automated test button trigger and minimalist report results for the test.
how to add the test :
- create a test file inside `tests` folder
- the test file must be named with `test_*.py` pattern
- extend the `unittest.TestCase` class
- create a method with a `test_*` pattern, so unittest can detect the method as a test method.
=> Implement minimal examples of automated tests

BakeToLayer.py, Layer.py, Mask.py, ui.py
=> Add a button to rebake all baked images

BakeToLayer.py, ui.py
Add `Rebake all Images` operator, it will rebake all `Bake to Layer` types (AO, Cavity, Bevel, etc). The edge detect mask bake is not included yet.
=> Rebake all Images

Root.py
=> Allow customizing tree name from the quick node setup popup

Root.py
=> Simplify setting material name to tree name

image_ops.py, ui.py
The feature working using dbus command, recommendation from Slander on Discord: https://discord.com/channels/738286550646784023/739433600251985990/1360330459698958397
=> Open containing image folder linux

BakeTarget.py, Root.py, ui.py
Add new feature for copy/paste bake target
=> Copy paste for custom bake target

Layer.py
Previously, each decal referencing the same empty would create its own duplicate. Now, only one duplicate is created per unique original empty and reused across all relevant decals.
Additionally, this update ensures that animation drivers referencing the original empty are updated to target the correct duplicated object.
- Extracted decal duplication logic into a reusable function
- Prevented redundant empty duplication when shared
- Added support for updating driver targets on duplicated empties
- Applied to both decal layers and mask layers
=> Refactor decal empty duplication and update driver targets

Modifier.py, modifier_common.py, node_connections.py, versioning.py
=> Ramp affect option

Layer.py, ui.py
=> Allow adding layers from an asset library ucupaint material
